### ISSUE TITLE
purity issue in Fs2RabbitConfig

### ISSUE THREAD

**Issue by mberndt123** [gvolpe/fs2-rabbit#117]
Hi,

the [Documentation](https://gvolpe.github.io/fs2-rabbit/config.html) suggests using PureConfig to load the configuration. However there doesn't seem to be a pure, referentially transparent way to create the SSLContext that is needed for that; all the static factory methods to create an SSLContext throw exceptions or return null. Users are thus likely to end up with code like
```scala
  implicit val sslContextReader: ConfigReader[SSLContext] =
    ConfigReader[String].map(SSLContext.getInstance)
```
which performs side effects in an uncontrolled manner. Would you agree that this is an issue? There's probably a number of ways to tackle this issue, but before discussing them I'd first like to get a consensus that in an environment where side effects are generally visible in the types this is not an ideal behaviour.

**Comment by gvolpe** [comment]
Hi @mberndt123 ,

Probably adding a note on the documentation would suffice. `pureconfig` is still the recommended way for reading configuration values but since the creation of `SSLContext` is side-effectful is recommended to fill that value once your config is filled with the pure configuration values such as host, port, etc.

This is purposely left on he user's hand because I believe that's the best option. The user is free to choose how that `Fs2RabbitConfig` is filled with values and passed to the creation of the `Fs2Rabbit` interpreter.

---

This is one way to do it:

```scala
IO(SSLContext.getInstance("SSL").some).handleError(_ => none[SSLContext]).map { ctx =>
  val config = Fs2RabbitConfig(
    virtualHost = "/",
    host = "127.0.0.1",
    username = Some("guest"),
    password = Some("guest"),
    port = 5672,
    ssl = false,
    sslContext = ctx,
    connectionTimeout = 3,
    requeueOnNack = false
  )
  Fs2Rabbit[IO](config)
}.flatMap { implicit fs2Rabbit =>
  ResilientStream
    .run(new AckerConsumerDemo[IO]().program)
    .as(ExitCode.Success)
}
```

Feel free to send in a PR if you would like to document such use case.

**Comment by mberndt123** [comment]
> pureconfig is still the recommended way for reading configuration values but since the creation of SSLContext is side-effectful is recommended to fill that value once your config is filled with the pure configuration values such as host, port, etc.

How exactly would that work? After all the whole point of pureconfig is that I don't need to worry about parsing the configuration object itself. I only need to provide `ConfigReader` instances for the individual fields and pureconfig will figure out how to parse the object for me. But in this case that requires a `ConfigReader[SSLContext]`, and there's no way to do that in a pure way. So frankly I can't see how to idiomatically parse an Fs2RabbitConfig using pureconfig. Your example code works around this issue by not using pureconfig at all.

**Comment by mberndt123** [comment]
One way would be to sidestep the issue entirely by removing `sslContext` from `Fs2RabbitConfig` entirely and pass it as a separate argument to `Fs2Rabbit.apply`. Of course the downside here is that you can't configure the SSL Context from the configuration at all (or you have to do it manually). 

Another solution would be to add an `F[_]` type parameter to `Fs2RabbitConfig` and change the type of `sslContext` to `Option[F[SSLContext]]`. Then you can do something like
```scala
implicit def sslContextReader[F[_]: Sync] =
  ConfigReader[String].map(s => Sync[F].delay(SSLContext.getInstance(s)))
```
This way everything is pure and very flexible, since the user is free to create the SSL Context in any way they see fit based on the configuration. Of course it's a bit unusual to have `F` things in the configuration…

**Comment by gvolpe** [comment]
Thanks for the input @mberndt123 , I'll cut a release with these changes later today. Just out of curiosity are you using `fs2-rabbit` in production?

**Comment by gvolpe** [comment]
Awesome, make sure to add it to the list of Adopters ;)
