### ISSUE TITLE
Create a single ConnectionFactory

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#120]
Even when invoking `createConnectionChannel` multiple times it seems unnecessary to create more than on `ConnectionFactory` as it internally has a "shared executor" and performs many other allocations when created.

For more information see the discussion on #118

**Comment by mberndt123** [comment]
The `sharedExecutor` thing actually looks interesting. Because `ConnectionFactory` only has a default constructor, meaning that `sharedExecutor` is null unless you set a value for it, which you don't. Yet the library still works, I wonder what's going on :thinking:

**Comment by gvolpe** [comment]
Java ¯\_(ツ)_/¯

**Comment by mberndt123** [comment]
Nice, thanks
