### ISSUE TITLE
Consider making AmqpEnvelope generic

### ISSUE THREAD

**Issue by mberndt123** [gvolpe/fs2-rabbit#123]
I noticed that the `AmqpMessage` class is generic, but the `AmqpEnvelope` class isn't. Is there a specific reason for that? Because it seems to me that making `AmqpEnvelope` generic would be quite useful, one often needs to pass around the payload together with the metadata (e. g. to Ack or Nack a message later).

**Comment by mberndt123** [comment]
If you're interested in this change, I can submit a pull request

**Comment by gvolpe** [comment]
Go ahead please! The payload was initially defined as a String for convenience and never changed.

**Comment by mberndt123** [comment]
OK, I can't really say when I'll get around to this though

**Comment by gvolpe** [comment]
No worries, if I can take it before hand I'll let you know here, I might have some time to kill this weekend while on a plane :)
