### ISSUE TITLE
Release 1.0-RC5

### ISSUE THREAD

**Issue by mberndt123** [gvolpe/fs2-rabbit#130]
Hi @gvolpe,

we need the ability to deal with binary messages in our program, which is easy with our recent changes (`EnvelopeDecoder`). Could you make an 1.0-RC5 release?

// edit: thinking about it, this isn't very urgent. We can publish a release on our internal Nexus, so no need to hurry.

**Comment by gvolpe** [comment]
Sure, I'll find some time to do it this afternoon (currently at SBTB).

**Comment by gvolpe** [comment]
Currently synchronizing with Maven Central. Release notes: https://github.com/gvolpe/fs2-rabbit/releases/tag/1.0-RC5

**Comment by mberndt123** [comment]
:+1: thanks!
