### ISSUE TITLE
Termination of RabbitMQ ignored by the connection

### ISSUE THREAD

**Issue by iRevive** [gvolpe/fs2-rabbit#141]
Reproducing flow:
1) Start RabbitMQ;
2) Open connection to RabbitMQ;
3) Stop RabbitMQ;
4) No error produced by a connection stream;

RabbitMQ client provides automatic recovery mechanism, but I'm not sure that it will be very useful.
From my perspective, recovery management should be done manually:
1) factory.setAutomaticRecoveryEnabled(false)
2) connection.addShutdownListener(shutdownCause => { recovery logic? })

Right now I have no idea how it can be implemented because the shutdown listener is async. If you will suggest a possible solution, I can try to work on it.

**Comment by gvolpe** [comment]
Sure. I'll give it a look tomorrow :)
