### ISSUE TITLE
Failover to next node if current node becomes unavailable

### ISSUE THREAD

**Issue by JanGe** [gvolpe/fs2-rabbit#155]
Hey @gvolpe ,
while evaluating your very promising library for use in a new service, I noticed that specifying multiple nodes of the same RabbitMQ cluster does not seem to be supported. The expectation would be to have the service automatically establish a connection to node B in case node A becomes unreachable, if both, node A and B are specified in the configuration.

I tried to work around this by defining multiple `Fs2RabbitConfig`s, instantiating one `Fs2Rabbit[F]` for each of them and then calling my own `createConnectionChannel()` to pick the first successful connection:

```scala
object Fs2RabbitUtil {

  private val logger = getLogger

  def createConnectionChannel[F[_]: Sync](
      nodes: List[Fs2Rabbit[F]]
  ): Stream[F, (Fs2Rabbit[F], AMQPChannel)] =
    nodes match {
      case node :: otherNodes =>
        (
          for {
            channel <- node.createConnectionChannel
            _       <- Stream.eval(Sync[F].delay(logger.info("Connected to RabbitMQ node.")))
          } yield (node, channel)
        ) handleErrorWith {
          case NonFatal(e) =>
            for {
              _       <- Stream.eval(Sync[F].delay(logger.warn(e)(s"Connection attempt to RabbitMQ node failed.")))
              channel <- createConnectionChannel(otherNodes)
            } yield channel
        }
      case List() => Stream.raiseError[F](new Exception(s"Connection attempts to all RabbitMQ nodes failed."))
    }
}
```

In connection with `ResilientStream.run()` I would have expected this to be enough to fail the stream in case a node becomes unreachable and then `createConnectionChannel` would pick the next node and restart the stream. However `amqp-client` only knows about one node and since [automatic recovery is not disabled](https://github.com/gvolpe/fs2-rabbit/blob/deeeae432a3f2c4293307fcb1ca99c5d4fe79233/core/src/main/scala/com/github/gvolpe/fs2rabbit/interpreter/ConnectionStream.scala#L64), `amqp-client` will try to reconnect to the same node over and over again instead of letting the stream fail.

There's two possible solutions to support failover that I can think of:
- Disable automatic recovery in `amqp-client`'s `ConnectionFactory` and let the stream fail. Users of the library would then have to handle the failover themselves.
- Support multiple nodes in `Fs2RabbitConfig` and pass them on to `amqp-client`, e.g.:
    ```scala
    Fs2RabbitConfig(
        nodes = List(
            Fs2RabbitNodeConfig(
                host = "host1.example.net",
                port = 5672
            ),
            Fs2RabbitNodeConfig(
                host = "host2.example.net",
                port = 5672
            )
        ),
        virtualHost = "/",
        connectionTimeout = 10,
        ssl = false,
        username = None,
        password = None,
        requeueOnNack = true,
        internalQueueSize = None
     )
    ```
    `amqp-client` [already supports configuring multiple nodes](https://www.rabbitmq.com/api-guide.html#address-array) and [will fall back to the other nodes automatically](https://www.rabbitmq.com/api-guide.html#connection-recovery).

**Comment by gvolpe** [comment]
Hi @JanGe ,

The second option seems to be the best one but I think it'd be worth adding another flag in `Fs2RabbitConfig` to indicate whether we want to disable automatic recovery in the `ConnectionFactory` (enabled by default).

This should be an easy PR, would you like to give it a shot?

**Comment by JanGe** [comment]
Sure, I can open a PR for that. Do you prefer a breaking change in the config (remove `host`/`port` at root level) or keep it backwards compatible (keep `host`/`port` at root level as fallback)?

**Comment by gvolpe** [comment]
That's a good question. I think it needs to be a breaking change. I propose to change the current definition and overload the apply method for convenience for people using it as a single node. I'm not sure on whether this breaks binary compatibility (there's no `MiMa` set up yet...).

```scala
case class Fs2RabbitNodeConfig(
  host: String,
  port: Int
  )
  
case class Fs2RabbitConfig(
    nodes: List[Fs2RabbitNodeConfig],
    virtualHost: String,
    connectionTimeout: Int,
    ssl: Boolean,
    username: Option[String],
    password: Option[String],
    requeueOnNack: Boolean,
    internalQueueSize: Option[Int]
)

object Fs2RabbitConfig {
  def apply(
    host: String,
    port: Int,
    virtualHost: String,
    connectionTimeout: Int,
    ssl: Boolean,
    username: Option[String],
    password: Option[String],
    requeueOnNack: Boolean,
    internalQueueSize: Option[Int]
  ): Fs2RabbitConfig = Fs2RabbitConfig(
      nodes = List(Fs2RabbitNodeConfig(host, port)),
      virtualHost = virtualHost,
      connectionTimeout = connectionTimeout,
      ssl = ssl,
      username = username,
      password = password,
      requeueOnNack = requeueOnNack,
      internalQueueSize = internalQueueSize
    )
}
```
