### ISSUE TITLE
Allow multiple channels per connection

### ISSUE THREAD

**Issue by DougC** [gvolpe/fs2-rabbit#186]
`ConnectionStream.createConnectionChannel` creates both a connection and a channel and there doesn't seem to be a way of creating multiple channels over a single connection, unless I'm missing something. According to https://stackoverflow.com/questions/18418936/rabbitmq-and-relationship-between-channel-and-connection, the rabbitmq model favours an approach of creating multiple channels within an application over a single connection to the server to reduce the amount of resources used. This is also important in my application where we're connecting to a Rabbit-as-a-service server which has a limited number of connections available.

It would be great to have some mechanism to create additional channels on an open connection.

**Comment by gvolpe** [comment]
Hi @DougC , nice seeing you around here!

Thanks for reporting it, I swear I had a *déjà vu* when I saw this issue and I believed this was already solved but it seems not.

It definitely makes sense to have this. If you would like to work on a PR I'd gladly take it otherwise I'll pick it up whenever I find some time :)

**Comment by DougC** [comment]
Hi @gvolpe! I've been giving it some thought overnight and wondering if multiple channels on a connection actually adds much benefit to an application since all activities will be serialised onto the channel anyway. So would it make sense to simply open one connection/channel pair and re-use it for all activities, in which case there would be no need for any change to `fs2-rabbit`? So I've done some investigation and I'm pretty sure that there is benefit in making the change. Here are my thoughts:

* com.rabbitmq.client.Channel implementations, as far as I can tell, are not thread-safe (which matches with what the docs say). Although deep down the `transmit` function synchronises on a mutex that protects the channel, there are other places, such as incrementing the sequence number during transmit, that aren't thread-safe.
* fs2-rabbit AMQPClient doesn't add any additional thread-safety to the channel (e.g. wrapping in a Ref), which is fair enough - no need to add the overhead.
* The AMQP framing protocol multiplexes traffic on the connection and interleaves data from multiple channels, which means that small messages won't get delayed behind large messages, which would be the case if all the messages were sent down one channel.

I'll try and find some time in the next couple of days to put together a PR.

Thanks for providing this very handy library!

**Comment by DougC** [comment]
Thanks for the merge. Any thoughts on when you're planning the next release?

**Comment by gvolpe** [comment]
I'll publish a snapshot in a few minutes with these changes. I'd like to make a release as soon as #150 gets done (I'm planning to work on it these days, more likely next week).

**Comment by gvolpe** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/github/gvolpe/fs2-rabbit_2.12/1.2.1-SNAPSHOT/

**Comment by DougC** [comment]
Thanks :-)
