### ISSUE TITLE
Add support for different types of queueUnbind

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#21]
Implement these methods:

- queueUnbind(String queue, String exchange, String routingKey)
- queueUnbind(String queue, String exchange, String routingKey, Map<String,Object> arguments)

See how bindQueue is already implemented.

Check the signatures in the java doc of the official java client:
https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/Channel.html

**Comment by cdelmas** [comment]
As far as I can see, both are implemented. I think I pushed the missing one by mistake along with the exchangeUnbind pull request.

**Comment by cdelmas** [comment]
As far as I can see, both are implemented. I think I pushed the missing one by mistake along with the exchangeUnbind pull request.
