### ISSUE TITLE
Add support for different types of basicPublish

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#24]
Implement these methods:

- basicPublish(String exchange, String routingKey, AMQP.BasicProperties props, byte[] body) [IMPLEMENTED]
- basicPublish(String exchange, String routingKey, boolean mandatory, AMQP.BasicProperties props, byte[] body) 
- basicPublish(String exchange, String routingKey, boolean mandatory, boolean immediate, AMQP.BasicProperties props, byte[] body)

Check the signatures in the java doc of the official java client:
https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/Channel.html

**Comment by cdelmas** [comment]
To implement both mandatory and immediate, shouldn't we add the notion of "ReturnListener" (as a  ReturnStream or something like that) ? Or maybe it is another separate feature?
My thoughts are: using mandatory or immediate without checking the return is useless. What do you think about that?

**Comment by gvolpe** [comment]
@cdelmas I'm not sure I follow. Both `basicPublish` methods return `void` in the Java driver. What do you mean with "checking the return"?

**Comment by cdelmas** [comment]
When using the mandatory and/or immediate flags, you expect the server to return the message if it was not routed. For that, the Java SDK `Channel` allows to add a `ReturnListener`, in order to get back the message and do something adequate.

**Comment by gvolpe** [comment]
Oh I see now, not sure how I'd go about it, I'll need to look into the API. With the Java driver one needs to guess what to expect... 

Going to sleep soon but feel free to propose something. I'll try to give it a read to the API these days.

**Comment by gvolpe** [comment]
@cdelmas just to let you know I'm working on this. Modifying the publishing algebra for now and registering the listeners on the `channel` seems to work. Still need to add tests but I believe a PR will be coming soon.

I found the interface you were talking about:

```java
/**
 * Implement this interface in order to be notified of failed
 * deliveries when basicPublish is called with "mandatory" or
 * "immediate" flags set.
 * For a lambda-oriented syntax, use {@link ReturnCallback}.
 * @see Channel#basicPublish
 */
public interface ReturnListener {
    void handleReturn(int replyCode,
            String replyText,
            String exchange,
            String routingKey,
            AMQP.BasicProperties properties,
            byte[] body)
        throws IOException;
}
```

**Comment by gvolpe** [comment]
More information that I'd like to add to the docs:

### bit mandatory

This flag tells the server how to react if the message cannot be routed to a queue. If this flag is set, the server will return an unroutable message with a Return method. If this flag is zero, the server silently drops the message.

The server SHOULD implement the mandatory flag.

### bit immediate

This flag tells the server how to react if the message cannot be routed to a queue consumer immediately. If this flag is set, the server will return an undeliverable message with a Return method. If this flag is zero, the server will queue the message, but with no guarantee that it will ever be consumed.

The server SHOULD implement the immediate flag.

Source: https://www.rabbitmq.com/amqp-0-9-1-reference.html
