### ISSUE TITLE
Add support for different types of queueDelete

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#26]
Implement these methods:

- queueDelete(String queue)
- queueDelete(String queue, boolean ifUnused, boolean ifEmpty)
- queueDeleteNoWait(String queue, boolean ifUnused, boolean ifEmpty)

Check the signatures in the java doc of the official java client:
https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/Channel.html

**Comment by insdami** [comment]
I think this is already implemented https://github.com/gvolpe/fs2-rabbit/blob/master/core/src/main/scala/com/github/gvolpe/fs2rabbit/algebra/AMQPClient.scala#L49

**Comment by gvolpe** [comment]
That'd be super nice to have. Go ahead :+1:
