### ISSUE TITLE
Implement queueDelete(String queue)

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#27]
Bare in mind that fs2-rabbit is just a wrapper for the AMQP Java client. So, whenever adding a new method that is supported by the native client, the procedure will be more or less the same:

1. Check the signatures in the java doc of the official java client:
https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/Channel.html
2. For this case, the return type is AMQP.Queue.DeleteOk so in fs2-rabbit it will be Stream[F, Queue.DeleteOk]
3. Add the new method at the end of the Fs2Rabbit file.
4. Add scala doc comments to the new method. Take a look at the existent methods but in general it could be more or less similar to the Java client docs. This is the one for this method: "Delete a queue, without regard for whether it is in use or has messages on it"
5. Add a unit test in the file Fs2RabbitSpec: I can help you out with this part since it's not as trivial as adding the new method and sometimes it might be okay to just invoke the method on an existent test instead of creating a new one.

HINT: Look at the existent method [bindQueue](https://github.com/gvolpe/fs2-rabbit/blob/master/core/src/main/scala/com/github/gvolpe/fs2rabbit/Fs2Rabbit.scala#L242), this one will be very similar ;)

Thanks for contributing!

**Comment by gheine** [comment]
Taking this one

**Comment by gvolpe** [comment]
Awesome @gheine !
