### ISSUE TITLE
Stable dependencies and a temporary fork of fs2-rabbit

### ISSUE THREAD

**Issue by orium** [gvolpe/fs2-rabbit#78]
Hi @gvolpe,

We are using fs2-rabbit in production and because of that we don't want to use unstable libraries which version 0.8 currently would force us to (cats-effect, fs2, and circe).  We have therefore forked your project in  https://github.com/ITV/fs2-rabbit.  That fork is basically the same thing as your project but with stable versions of the dependencies (and with #76 landed).

We don't want this to be a permanent solution.  Ideally you would provide a stable version of fs2-rabbit that we could use.

Thanks!

**Comment by gvolpe** [comment]
Hi @orium,

That's an unfortunate situation :disappointed: but I think that's the best for now. 

We are all depending on a final `cats-effect` release (that has been delayed very much) and right now I don't have the time to maintain two different versions but I'd gladly make you a maintainer if you're interested, just drop me a line here or on Gitter.

**Comment by gvolpe** [comment]
Out of curiosity, what versions of `cats-effect` and `fs2` are you using?

The [0.7 release](https://github.com/gvolpe/fs2-rabbit/releases/tag/0.7) is built on Cats Effect 1.0.0-RC and Fs2 0.10.4.

**Comment by orium** [comment]
> Out of curiosity, what versions of cats-effect and fs2 are you using?
>
> The 0.7 release is built on Cats Effect 1.0.0-RC and Fs2 0.10.4.

Cats effect 0.10.1 and fs2 0.10.5.  Bumping the cats effect to 1.0 would force use to use an unstable http4s (0.19.0-M1), which we really don't want to do.

> That's an unfortunate situation :disappointed: but I think that's the best for now.

I agree.  Every other solution I can think of sucks even more.  Fortunately this should not be a problem for too long since cats-effect 1.0 will likely be release in the next few weeks, then fs2 1.0 hopefully will not take too long after that.  Http4s should follow: in https://github.com/http4s/http4s/issues/1797 they say they want to release http4s 0.19 on fs2/effect-1.0 ASAP.

If everything goes well we should be able to kill or fork in the next few months :) :crossed_fingers:
