### ISSUE TITLE
Support all standard properties in AmqpProperties

### ISSUE THREAD

**Issue by cdelmas** [gvolpe/fs2-rabbit#85]
It looks like there is no way to add a correlation id or a message id for a message. By extension, it would be nice to support all the standard properties (user_id, type, app_id, ...) in addition of those which are already supported (content_type, content_encoding, priority, deliveryMode).

**Comment by gvolpe** [comment]
Hi @cdelmas , please feel free to send in a PR. 

At the moment my time is very limited and can't do much more than releasing new versions and review PRs.
