### ISSUE TITLE
Add support for different types of exchangeDeclare

### ISSUE THREAD

**Issue by gvolpe** [gvolpe/fs2-rabbit#9]
Currently the library implements only one of this flavor, but there are more to add:

- [x] exchangeDeclare(String exchange, BuiltinExchangeType type) [IMPLEMENTED (*)]
- [x] exchangeDeclare(String exchange, BuiltinExchangeType type, boolean durable)
- [x] exchangeDeclare(String exchange, BuiltinExchangeType type, boolean durable, boolean autoDelete, boolean internal, Map<String,Object> arguments)
- [x] exchangeDeclare(String exchange, BuiltinExchangeType type, boolean durable, boolean autoDelete, Map<String,Object> arguments)
- [x] exchangeDeclareNoWait(String exchange, BuiltinExchangeType type, boolean durable, boolean autoDelete, boolean internal, Map<String,Object> arguments)
- [x] exchangeDeclarePassive(String name)

Check the signatures in the java doc of the official java client:
https://rabbitmq.github.io/rabbitmq-java-client/api/current/com/rabbitmq/client/Channel.html

(*) Fs2Rabbit#L164

**Comment by orium** [comment]
#82 added support for those `exchangeDeclare(...)` :)

**Comment by gvolpe** [comment]
Closed by #87
